#!/bin/bash

# helper functions
json_array() {
  echo -n '['
  while [ $# -gt 0 ]; do
    x=${1//\\/\\\\}
    echo -n \""${x//\"/\\\"}"\"
    [ $# -gt 1 ] && echo -n ', '
    shift
  done
  echo ']'
}

ssjs_clear_scanner_device() {
  # delete previously detected scanservjs device and output to stderr
  echo $(curl -X "DELETE" "$SSJS_PROTOCOL://$SSJS_HOST:$SSJS_PORT/context" \
	  -H 'Connection: keep-alive' \
	  -H 'Accept: */*' \
	  --compressed \
	  --insecure) >&2
}

ssjs_get_scanner_device() {
 # get new device name and return to stdout
  device=$(curl "$SSJS_PROTOCOL://$SSJS_HOST:$SSJS_PORT/context" \
	  -H 'Connection: keep-alive' \
	  -H 'Accept: */*' \
	  --compressed \
	  --insecure |  jq -r '.devices[0].id')
  echo $device
}

